---
version: 2
plan:
  project-key: THAL
  key: PUL
  name: Hello-World-Linux-1
  description: Does git Pull on Bamboo-Hello_world and compiles it in Gradle
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - Default Job
Default Job:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash
        #create a 2gb file
        #dd if=/dev/urandom of=./2gb-file bs=1024 count=2048000 iflag=fullblock
        dd if=/dev/urandom of=./2mb-file bs=1024 count=2048 iflag=fullblock
      working-dir: app/src/main/resources
      description: Build Large File
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/sh

        javaApp=app/build/libs/app.jar

        #Clean build environment
        ./gradlew clean build

        #package Hellow World into a jar file
        ./gradlew jar

        if test -f "$javaApp";
                then
        echo "success, jar file exists"
        exit  0
                else
        echo "jar file is missing"
        exit  1

        fi
      description: Gradle clean build
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/bash

        java -jar app/build/libs/app.jar
      description: Display Hello world
  - script:
      interpreter: SHELL
      scripts:
      - |-
        #!/bin/sh

        CorrectSize=2000000

        ActualSize=$(cat app/build/libs/app.jar | wc -c)
        if [ "$ActualSize" -gt  "$CorrectSize" ]
                then
                        exit  0
                else
        echo "Size of the java file is too small"
        exit  1

        fi
      description: Java App size
  artifacts:
  - name: App .jar
    location: app/build/libs/
    pattern: app.jar
    shared: false
    required: true
  requirements:
  - agentname: Linux-1
  artifact-subscriptions: []
repositories:
- Bamboo-hello-world:
    scope: project
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications:
- events:
  - plan-completed
  recipients:
  - emails:
    - john.harris@isostech.dev
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans:
  - THAL-HEL
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: THAL-PUL
plan-permissions:
- users:
  - admin
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - viewConfiguration
...
